<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__.'/src')
    ->in(__DIR__.'/tests');

$rules = [
    "@PSR12" => true,
    "@PSR12:risky" => true,
    'array_indentation' => true,
    'array_syntax' => true,
    'assign_null_coalescing_to_coalesce_equal' => true,
    'attribute_empty_parentheses' => true,
    'binary_operator_spaces' => true,
    'blank_line_after_namespace' => true,
    'blank_line_after_opening_tag' => true,
    'blank_line_before_statement' => [
        'statements' => [
            'break',
            'continue',
            'declare',
            'do',
            'exit',
            'for',
            'foreach',
            'goto',
            'if',
            'include',
            'include_once',
            'require',
            'require_once',
            'return',
            'switch',
            'throw',
            'try',
            'while',
        ],
    ],
    'blank_line_between_import_groups' => false,
    'blank_lines_before_namespace' => [
        'max_line_breaks' => 2,
        'min_line_breaks' => 2,
    ],
    'braces_position' => [
        'classes_opening_brace' => 'same_line',
        'functions_opening_brace' => 'same_line',
        'control_structures_opening_brace' => 'same_line',
        'anonymous_classes_opening_brace' => 'same_line',
        'anonymous_functions_opening_brace' => 'same_line',
    ],
    'cast_spaces' => ['space' => 'single'],
    'class_definition' => [
        'multi_line_extends_each_single_line' => true,
        'single_item_single_line' => true,
        'single_line' => true,
        'space_before_parenthesis' => true,
    ],
    'class_reference_name_casing' => true,
    'clean_namespace' => true,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'combine_nested_dirname' => true,
    'compact_nullable_type_declaration' => true,
    'concat_space' => ['spacing' => 'none'],
    'constant_case' => ['case' => 'lower'],
    'control_structure_braces' => true,
    'control_structure_continuation_position' => [
        'position' => 'same_line',
    ],
    'date_time_immutable' => true,
    'declare_equal_normalize' => ['space' => 'none'],
    'declare_parentheses' => true,
    'dir_constant' => true,
    'elseif' => true,
    'empty_loop_body' => true,
    'explicit_indirect_variable' => true,
    'explicit_string_variable' => false,
    'final_class' => true,
    'final_public_method_for_abstract_class' => true,
    'full_opening_tag' => true,
    'function_declaration' => [
        'closure_fn_spacing' => 'one',
        'closure_function_spacing' => 'one',
        'trailing_comma_single_line' => false,
    ],
    'get_class_to_class_keyword' => true,
    'global_namespace_import' => true,
    'heredoc_indentation' => [
        'indentation' => 'same_as_start',
    ],
    'implode_call' => true,
    'indentation_type' => true,
    'integer_literal_case' => true,
    'is_null' => true,
    'lambda_not_used_import' => true,
    'line_ending' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' => ['syntax' => 'short'],
    'logical_operators' => true,
    'long_to_shorthand_operator' => true,
    'lowercase_cast' => true,
    'lowercase_keywords' => true,
    'lowercase_static_reference' => true,
    'magic_constant_casing' => true,
    'magic_method_casing' => true,
    'method_argument_space' => [
        'after_heredoc' => false,
        'attribute_placement' => ['ignore', 'same_line', 'standalone'][0],
        'keep_multiple_spaces_after_comma' => false,
        'on_multiline' => ['ignore', 'ensure_single_line', 'ensure_fully_multiline'][2],
    ],
    'method_chaining_indentation' => true,
    'modernize_strpos' => true,
    'modernize_types_casting' => true,
    'multiline_comment_opening_closing' => true,
    'multiline_promoted_properties' => [
        'keep_blank_lines' => false,
        'minimum_number_of_parameters' => 3,
    ],
    'multiline_whitespace_before_semicolons' => [
        'strategy' => 'no_multi_line',
    ],
    'native_function_casing' => true,
    'native_type_declaration_casing' => true,
    'new_expression_parentheses' => [
        'use_parentheses' => true,
    ],
    'new_with_parentheses' => [
        'anonymous_class' => true,
        'named_class' => true,
    ],
    'no_alias_language_construct_call' => true,
    'no_blank_lines_after_class_opening' => true,
    'no_blank_lines_after_phpdoc' => false,
    'no_closing_tag' => true,
    'no_empty_comment' => true,
    'no_empty_phpdoc' => true,
    'no_empty_statement' => true,
    'no_extra_blank_lines' => [
        'tokens' => [
            'attribute',
            'break',
            'case',
            'comma',
            'continue',
            'curly_brace_block',
            'default',
            'extra',
            'parenthesis_brace_block',
            'return',
            'square_brace_block',
            'switch',
            'throw',
            'use',
        ],
    ],
    'no_leading_import_slash' => true,
    'no_leading_namespace_whitespace' => true,
    'no_mixed_echo_print' => ['use' => 'echo'],
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_multiple_statements_per_line' => true,
    'no_null_property_initialization' => true,
    'no_short_bool_cast' => true,
    'no_singleline_whitespace_before_semicolons' => true,
    'no_space_around_double_colon' => true,
    'no_spaces_after_function_name' => true,
    'no_spaces_around_offset' => [
        'positions' => [
            'inside',
            'outside',
        ],
    ],
    'no_superfluous_elseif' => true,
    'no_superfluous_phpdoc_tags' => [
        'allow_hidden_params' => false,
        'allow_mixed' => false,
        'allow_unused_params' => false,
        'remove_inheritdoc' => true,
    ],
    'no_trailing_comma_in_singleline' => [
        'elements' => [
            'arguments',
            'array',
            'array_destructuring',
            'group_import',
        ],
    ],
    'no_trailing_whitespace' => true,
    'no_trailing_whitespace_in_comment' => true,
    'no_unneeded_braces' => [
        'namespaces' => true,
    ],
    'no_unneeded_control_parentheses' => [
        'statements' => [
            'break',
            'clone',
            'continue',
            'echo_print',
            'negative_instanceof',
            'others',
            'return',
            'switch_case',
            'yield',
            'yield_from',
        ],
    ],
    'no_unset_cast' => true,
    'no_unset_on_property' => true,
    'no_unused_imports' => true,
    'no_useless_concat_operator' => [
        'juggle_simple_strings' => false,
    ],
    'no_useless_else' => true,
    'no_useless_nullsafe_operator' => true,
    'no_useless_printf' => true,
    'no_useless_return' => true,
    'no_useless_sprintf' => true,
    'no_whitespace_before_comma_in_array' => [
        'after_heredoc' => false,
    ],
    'no_whitespace_in_blank_line' => true,
    'non_printable_character' => true,
    'normalize_index_brace' => true,
    'not_operator_with_space' => false,
    'not_operator_with_successor_space' => false,
    'nullable_type_declaration' => [
        'syntax' => 'question_mark',
    ],
    'object_operator_without_whitespace' => true,
    'octal_notation' => true,
    'operator_linebreak' => [
        'only_booleans' => false,
        'position' => 'beginning',
    ],
    'ordered_class_elements' => [
        'case_sensitive' => false,
        'order' => [
            'use_trait',
            'case',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'method_public_static',
            'method_private_static',
            'construct',
            'method:configure',
            'method:__invoke',
            'phpunit',
            'method_public',
            'method_protected',
            'method_private',
            'magic',
            'destruct',
        ]
    ],
    'ordered_imports' => [
        'case_sensitive' => false,
        'imports_order' => ['const', 'class', 'function'],
    ],
    'ordered_interfaces' => true,
    'phpdoc_align' => [
        'align' => 'left',
    ],
    'phpdoc_indent' => true,
    'phpdoc_no_alias_tag' => true,
    'phpdoc_no_empty_return' => true,
    'phpdoc_no_package' => true,
    'phpdoc_no_useless_inheritdoc' => true,
    'phpdoc_order' => [
        'order' => [
            'param',
            'return',
            'throws',
        ],
    ],
    'phpdoc_param_order' => true,
    'phpdoc_scalar' => true,
    'phpdoc_single_line_var_spacing' => true,
    'phpdoc_trim' => true,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_types' => true,
    'phpdoc_var_annotation_correct_order' => true,
    'phpdoc_var_without_name' => true,
    'protected_to_private' => true,
    'return_assignment' => false,
    'return_type_declaration' => [
        'space_before' => 'none',
    ],
    'self_accessor' => true,
    'self_static_accessor' => true,
    'semicolon_after_instruction' => false,
    'short_scalar_cast' => true,
    'simple_to_complex_string_variable' => true,
    'simplified_if_return' => true,
    'simplified_null_return' => true,
    'single_blank_line_at_eof' => true,
    'single_class_element_per_statement' => true,
    'single_import_per_statement' => true,
    'single_line_after_imports' => true,
    'single_line_comment_spacing' => true,
    'single_line_comment_style' => [
        'comment_types' => [],
    ],
    'single_line_empty_body' => false,
    'single_line_throw' => false,
    'single_quote' => false,
    'single_space_around_construct' => [
        'constructs_contain_a_single_space' => ['yield_from'],
        'constructs_followed_by_a_single_space' => [
            'abstract',
            'as',
            'attribute',
            'break',
            'case',
            'catch',
            'class',
            'clone',
            'comment',
            'const',
            'const_import',
            'continue',
            'do',
            'echo',
            'else',
            'elseif',
            'enum',
            'extends',
            'final',
            'finally',
            'for',
            'foreach',
            'function',
            'function_import',
            'global',
            'goto',
            'if',
            'implements',
            'include',
            'include_once',
            'instanceof',
            'insteadof',
            'interface',
            'match',
            'named_argument',
            'namespace',
            'new',
            'open_tag_with_echo',
            'php_doc',
            'php_open',
            'print',
            'private',
            'private_set',
            'protected',
            'protected_set',
            'public',
            'public_set',
            'readonly',
            'require',
            'require_once',
            'return',
            'static',
            'switch',
            'throw',
            'trait',
            'try',
            'type_colon',
            'use',
            'use_lambda',
            'use_trait',
            'var',
            'while',
            'yield',
            'yield_from',
        ],
        'constructs_preceded_by_a_single_space' => [
            'as',
            'else',
            'elseif',
            'use_lambda',
        ],
    ],
    'single_trait_insert_per_statement' => true,
    'space_after_semicolon' => true,
    'spaces_inside_parentheses' => false,
    'standardize_not_equals' => true,
    'statement_indentation' => true,
    'switch_case_semicolon_to_colon' => true,
    'switch_case_space' => true,
    'switch_continue_to_break' => true,
    'ternary_operator_spaces' => true,
    'ternary_to_elvis_operator' => true,
    'ternary_to_null_coalescing' => true,
    'trailing_comma_in_multiline' => [
        'after_heredoc' => true,
        'elements' => [
            'arguments',
            'array_destructuring',
            'arrays',
            'match',
            'parameters',
        ],
    ],
    'trim_array_spaces' => true,
    'type_declaration_spaces' => true,
    'types_spaces' => [
        'space' => 'none',
        'space_multiple_catch' => 'none',
    ],
    'unary_operator_spaces' => false,
    'use_arrow_functions' => false,
    'visibility_required' => true,
    'void_return' => true,
    'whitespace_after_comma_in_array' => [
        'ensure_single_space' => true,
    ],
];

return (new PhpCsFixer\Config())
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRiskyAllowed(true)
    ->setFinder($finder)
    ->setRules($rules);
